### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by martin-fink**
Added a Dockerfile so people can run the script without having to install all the python dependencies.

This could also be published to dockerhub, so user could just reference the dockerfile without having to build it manually by themselves.

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/123)

### CODE REVIEW

**Comment by serhii73** [comment]
Hello @martin-fink How are you?
Thank you very much for your PR.
Sorry but I get a problem when I want start script with Docker.
```
➜ docker build -t place2live .
```
Then
```
➜ docker run -i place2live
```
And 
Screenshot from 2019-10-07 22-00-54
But if I run the script uses Python(without Docker), all work well.
Screenshot from 2019-10-07 22-01-46
Can you help me? 
Thank you very much!

**Comment by martin-fink** [comment]
Hi @serhii73, I'm fine, how are you?  
Thank you for your comment! I forgot to add the `-t` flag to the `docker run` command, so it did not allocate a tty, resulting in an error when printing colorized output. I updated the README with the correct command, which should be `docker run -it place2live`.

Thanks again!

**Comment by serhii73** [comment]
Thank you very much for your PR.

**Comment by serhii73** [comment]
Close #122

**Pull request merged**
