### PR TITLE
Remove code string

### PR DESCRIPTION
**Pull request by nikitaden03**
Remove coding string

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/64)

### CODE REVIEW

**Comment by nikitaden03** [comment]
close #64

**Comment by serhii73** [comment]
> close #64

https://github.com/serhii73/place2live/search?q=%23+-*-+coding%3A+utf-8+-*-&unscoped_q=%23+-*-+coding%3A+utf-8+-*-

**Comment by serhii73** [comment]
Thank you very much!

**Comment by serhii73** [comment]
> close #64

This is a mistake.

**Comment by serhii73** [comment]
Closed #57

**Pull request merged**
