### PR TITLE
Add max and min value

### PR DESCRIPTION
**Pull request by nikitaden03**
Added maximum and minimum value. If you have any complaints, will write me

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/45)

### CODE REVIEW

**Comment by serhii73** [comment]
@nikitaden03 
Thank you very much for your PR.
Please use [keywords](https://help.github.com/en/articles/closing-issues-using-keywords) for an automatically close issue.

**Comment by serhii73** [comment]
@nikitaden03  Also, please use these rules for writing git commits:
1. Separate subject from a body with a blank line
2. Limit the subject line to 50 characters
3. Capitalize the subject line
4. Do not end the subject line with a period
5. Use the imperative mood in the subject line
6. Wrap the body at 72 characters
7. Use the body to explain what and why vs. how

**Comment by serhii73** [comment]
Please, fix these problems - https://app.codacy.com/app/serhii73/place2live/pullRequest?prid=3871263

**Comment by serhii73** [comment]
___
*[where.py, line 8 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0npTh80qr0DEKq6Vz:-Lk0npTh80qr0DEKq6W-:b-5kdbw1) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L8)):*
> ```Python
> 
> def max_min_index(name_of_index):
>     """Return max and min number from list"""
> ```

The docstring is a phrase ending in a period.

**Comment by serhii73** [comment]
___
*[where.py, line 26 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0oRdiCxs1A-sW6rFI:-Lk0oRdiCxs1A-sW6rFJ:b-y9o72w) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L26)):*
> ```Python
> # it's tuple. For example freedomhouse_score look like
> # ([100.0, ['Sweden', 'Norway', 'Finland']], [1.0, 'Syria'])
> max_min_freedomhouse_score = max_min_index('freedomhouse_score')
> ```

Not need a minimum and the maximum score for `freedom house` data.

**Comment by serhii73** [comment]
___
*[where.py, line 62 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0osgP5JQ9P4_sZyLp:-Lk0osgP5JQ9P4_sZyLq:biopiy) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L62)):*
> ```Python
> your_safety_index = (
>     float(input("What is your safety index (higher is better)?\
>     The best score in the world is {}({}), the worst is {}({}) ".format(
> ```

Sorry, why 'format' better than 'f' string here?

**Comment by serhii73** [comment]
___
*[where.py, line 8 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0pV7_0QkzGddlpyca:-Lk0pV7_0QkzGddlpycb:b-e9jyri) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L8)):*
> ```Python
> 
> def max_min_index(name_of_index):
>     """Return max and min number from list"""
> ```

Sorry, `return number from a list`
What the `list`? Please, tell me more in doc string.

**Comment by serhii73** [comment]
___
*[where.py, line 11 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0q33D8_RH4LddttTB:-Lk0q33D8_RH4LddttTC:btaksbo) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L11)):*
> ```Python
>     max_value = [0, []]
>     min_value = [1000000, []]
>     for i, country in zip(list(df[name_of_index]), list(df['country'])):
> ```

`countries = list(df['country'])`
`indexes = list(df[name_of_index]`

**Comment by serhii73** [comment]
___
*[where.py, line 12 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0qUZv4LcFcfvv2mtP:-Lk0qUZv4LcFcfvv2mtQ:bc1f10j) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L12)):*
> ```Python
>     min_value = [1000000, []]
>     for i, country in zip(list(df[name_of_index]), list(df['country'])):
>         if str(i) != 'nan':
> ```

I think in `pandas` exist a better way how to find max or min values. What do you think about that?`

**Comment by serhii73** [comment]
___
*[where.py, line 8 at r2](https://reviewable.io/reviews/serhii73/place2live/45#-Lk0npTh80qr0DEKq6Vz:-Lk0rKW_-F9tYjatiC6V:b-pfpnuz) ([raw file](https://github.com/serhii73/place2live/blob/168978fa094ef4161baaf811a8b72ccfdb37b231/where.py#L8)):*
<details><summary><i>Previously, serhii73 wrote…</i></summary><blockquote>

The docstring is a phrase ending in a period.
</blockquote></details>

https://www.python.org/dev/peps/pep-0257/#id16

**Comment by serhii73** [comment]
@nikitaden03 If you have any questions, you can write me to a private message - https://gitter.im/serhii73

**Comment by nikitaden03** [comment]
Hello,
I redid the search for the maximum and minimum values, corrected the function documentation, replaced all the format with f lines and redid the code for PEP8, except the length of the lines.
close #38

**Comment by serhii73** [comment]
@nikitaden03 https://travis-ci.com/serhii73/place2live/builds/119634965

**Comment by serhii73** [comment]
___
*[where.py, line 14 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5ab5gB237JlTNQmdc:-Lk5ab5gB237JlTNQmdd:bvflosu) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L14)):*
> ```Python
> 
> 
> max_min_purchasing = max_min_index('purchasing_power_index')
> ```

`df[name_of_index].max()` showing only score. Can you extract data with name country?
```
In [12]: df['quality_of_life_index'].max()                                                     
Out[12]: 197.47
```
But I want extract for example  `quality_of_life_index = Switzerland: 197.47`
Because I want to show a message like 
```
In your country quality of life index is 115.98, the best score in the world is 197.47 in Switzerland, the worst is 0.0 in Venezuela
```
Maybe you will found better decision
```
In [37]: counrties_in_qol_index = df[['country', 'quality_of_life_index']].sort_values(by='quality_of_life_index').dropna()                                  

In [38]: list(counrties_in_qol_index['country'])[0], list(counrties_in_qol_index['quality_of_life_index'])[0]                                                
Out[38]: ('Venezuela', 0.0)

In [39]: list(counrties_in_qol_index['country'])[-1], list(counrties_in_qol_index['quality_of_life_index'])[-1]                                              
Out[39]: ('Switzerland', 197.47)

```

**Comment by serhii73** [comment]
___
*[where.py, line 14 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5ab5gB237JlTNQmdc:-Lk5azGS7xbZK0rjBgpt:bqu66an) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L14)):*
<details><summary><i>Previously, serhii73 wrote…</i></summary><blockquote>

`df[name_of_index].max()` showing only score. Can you extract data with name country?
```
In [12]: df['quality_of_life_index'].max()                                                     
Out[12]: 197.47
```
But I want extract for example  `quality_of_life_index = Switzerland: 197.47`
Because I want to show a message like 
```
In your country quality of life index is 115.98, the best score in the world is 197.47 in Switzerland, the worst is 0.0 in Venezuela
```
Maybe you will found better decision
```
In [37]: counrties_in_qol_index = df[['country', 'quality_of_life_index']].sort_values(by='quality_of_life_index').dropna()                                  

In [38]: list(counrties_in_qol_index['country'])[0], list(counrties_in_qol_index['quality_of_life_index'])[0]                                                
Out[38]: ('Venezuela', 0.0)

In [39]: list(counrties_in_qol_index['country'])[-1], list(counrties_in_qol_index['quality_of_life_index'])[-1]                                              
Out[39]: ('Switzerland', 197.47)

```
</blockquote></details>

Sorry, `The best score in the world is 136.43 (Gibraltar), the worst is 2.61 (Cuba)` - I see the message.

**Comment by serhii73** [comment]
___
*[where.py, line 7 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5bhyo-f8Xa0RjOWTb:-Lk5bhyo-f8Xa0RjOWTc:b-cy6vjg) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L7)):*
> ```Python
> 
> 
> def max_min_index(name_of_index):
> ```

Do you want to write a little small test for this function?
It will be brilliant.
You can use `pytest` for this.

**Comment by serhii73** [comment]
___
*[where.py, line 106 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5c4vd8xUXOZGRUWix:-Lk5c4vd8xUXOZGRUWiy:b-9r4s0) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L106)):*
> ```Python
>                 f"the worst is {max_min_property[1]} "
>                 f"({list(df[df.property_price_to_income_ratio == max_min_property[1]]['country'])[0]}) ")) or
>     your_property_price_to_income_ratio
> ```

`What is your house price to income ratio (lower is better)? The best score in the world is 455.51 (Somalia), the worst is 1.0 (Dominica)` - Error

**Comment by serhii73** [comment]
___
*[where.py, line 103 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5cRzT-o7TY9MuUyPP:-Lk5cRzUD9mA5VhsOrQC:b-38616u) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L103)):*
> ```Python
>                 f"The best score in the world is "
>                 f"{max_min_property[0]} "
>                 f"({list(df[df.property_price_to_income_ratio == max_min_property[0]]['country'])[0]}), "
> ```

Looks hard.
Can this be moved to a variable or function?

**Comment by serhii73** [comment]
___
*[where.py, line 127 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5cfxxBnN04_nYewy2:-Lk5cfxxBnN04_nYewy3:b-zhofph) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L127)):*
> ```Python
> 
> your_pollution_index = float(df[df.country == your_country]["pollution_index"])
> print(f"In your country pollution index is {your_pollution_index}")
> ```

`What is your traffic commute time index (lower is better)? The best score in the world is 120.0 (Aruba), the worst is 0.0 (Bhutan) ` - Error

**Comment by serhii73** [comment]
___
*[where.py, line 127 at r3](https://reviewable.io/reviews/serhii73/place2live/45#-Lk5d4hk0X17Bh6y1cY0:-Lk5d4hk0X17Bh6y1cY1:b-o6lida) ([raw file](https://github.com/serhii73/place2live/blob/e887458b46b38d5696ad193ffd10b3345c8853b3/where.py#L127)):*
> ```Python
> 
> your_pollution_index = float(df[df.country == your_country]["pollution_index"])
> print(f"In your country pollution index is {your_pollution_index}")
> ```

`What is your pollution index (lower is better)? The best score in the world is 108.05 (Congo), the worst is 10.63 (Us Virgin Islands) ` - Error

**Comment by serhii73** [comment]
Also, right now need fix conflicts @nikitaden03

**Comment by nikitaden03** [comment]
Hello,
I added testing, rewrote the result format returned by the max_min_index () function, added a function to print the question, and did all the code for PEP8. about the testing, I know them quite superficially, so I could make a stupid mistake. What i can do for improve my code?

**Comment by serhii73** [comment]
Screenshot from 2019-07-20 11-18-02
Travis must be green

**Comment by serhii73** [comment]
```
git checkout master
git pull origin master
```
Then come back on your branch and to do `git merge master`

**Comment by nikitaden03** [comment]
Sorry, 
I am not really understand,  why Travis CI Failed on flake8,  because my flake8 don't write anything.

**Comment by serhii73** [comment]
@nikitaden03 please,
```
pip install pre-commit
pre-commit run --all-files
```

**Comment by serhii73** [comment]
But first you need to fix 
`This branch has conflicts that must be resolved.`

**Comment by serhii73** [comment]
https://travis-ci.com/serhii73/place2live/builds/119823088

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 14 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIv3wt0Rs7EGd6SRdy:-LkIv3wt0Rs7EGd6SRdz:br2xzld) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L14)):*
> ```Python
> 
> 
> df = pd.read_csv("city/output/list_of_countries.csv")
> ```

Better use simple data frame for this. Because the file will be changed in the future.

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 5 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIvXz3C0HYEkOctC21:-LkIvXz3C0HYEkOctC22:bi466k) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L5)):*
> ```Python
> 
> 
> def max_min_index(name_of_index, name):
> ```

Please `import` this function from `where.py`

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 26 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIvhWk-5w0j7reBYey:-LkIvhWk-5w0j7reBYez:bkkpgnp) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L26)):*
> ```Python
>     ('pollution_index', df.pollution_index),
> ])
> def test_max_min_index(name_index, name):
> ```

Please, write documentation for this function.

**Comment by nikitaden03** [comment]
Can I take the df variable from where.py?

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 30 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIx3b15M-3_CdSJBk3:-LkIx3b262GErRnLLSm4:b-rdgg2p) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L30)):*
> ```Python
>     for i in df[name_index]:
>         if i != 'nan':
>             list_of_value.append(i)
> ```

`list_of_value = [i for i in df[name_index] if i != 'nan'] `

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 31 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIxCuh0X5lPBhoKXwz:-LkIxCuh0X5lPBhoKXx-:b6xr9ot) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L31)):*
> ```Python
>         if i != 'nan':
>             list_of_value.append(i)
>     max_value = max(list_of_value)
> ```

```
In [8]: max(list_of_value)                                                                     
Out[8]: 93.38

In [9]: df[name_index].max()                                                                   
Out[9]: 93.38
```

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 32 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIxMN1-buNSoqr3Guq:-LkIxMN1-buNSoqr3Gur:b-yhcq8q) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L32)):*
> ```Python
>             list_of_value.append(i)
>     max_value = max(list_of_value)
>     min_value = min(list_of_value)
> ```

```
In [10]: min(list_of_value) == df[name_index].min()                                            
Out[10]: True
```

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 33 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIy8tZ6pLIrhFL_Q8m:-LkIy8tZ6pLIrhFL_Q8n:bsw1dp4) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L33)):*
> ```Python
>     max_value = max(list_of_value)
>     min_value = min(list_of_value)
>     max_country = list(df[name == max_value]['country'])
> ```

```
In [37]: counrties_in_qol_index = df[['country', 'quality_of_life_index']].sort_values(by='quality_of_life_index').dropna()                                  

In [38]: list(counrties_in_qol_index['country'])[0], list(counrties_in_qol_index['quality_of_life_index'])[0]                                                
Out[38]: ('Venezuela', 0.0)

In [39]: list(counrties_in_qol_index['country'])[-1], list(counrties_in_qol_index['quality_of_life_index'])[-1]                                              
Out[39]: ('Switzerland', 197.47)
```
Is it not better? Why?

**Comment by serhii73** [comment]
___
*[test_maxminindex.py, line 37 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIyK9RDpDatRmXXvqV:-LkIyK9RDpDatRmXXvqW:b-ir2p1j) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/test_maxminindex.py#L37)):*
> ```Python
>     b = max_min_index(name_index, name) == ((max_value, max_country),
>                                             (min_value, min_country))
>     if not b:
> ```

Sorry, explain this code. Thanks.

**Comment by nikitaden03** [comment]
This is tantamount to assert max_min_index(name_index, name) == ((max_value, max_country),(min_value, min_country)). But I do not remember which test said to replace assert with this construction.

**Comment by serhii73** [comment]
___
*[where.py, line 18 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkJ-2fw7OCdKezPq9Pw:-LkJ-2fw7OCdKezPq9Px:b-ta8z7o) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/where.py#L18)):*
> ```Python
> def print_question(name_index, max_min_value, mood):
>     """Returns a question that asks the user about the status of a factor
>     in his country,also displays the maximum and minimum value of this factor
> ```

Need space after `also`

**Comment by serhii73** [comment]
___
*[where.py, line 16 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIzxZg8GnIGTpwKdDY:-LkIzxZg8GnIGTpwKdDZ:b-fyxd9u) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/where.py#L16)):*
> ```Python
> 
> 
> def print_question(name_index, max_min_value, mood):
> ```

```
In [35]: print(print_question.__doc__)                                                         
Returns a question that asks the user about the status of a factor
    in his country,also displays the maximum and minimum value of this factor
    in the world.
```
Is it readable?

**Comment by serhii73** [comment]
___
*[where.py, line 16 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIzxZg8GnIGTpwKdDY:-LkJ-QLx1b4sOl-Nc3uK:b-ctz2sr) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/where.py#L16)):*
<details><summary><i>Previously, serhii73 wrote…</i></summary><blockquote>

```
In [35]: print(print_question.__doc__)                                                         
Returns a question that asks the user about the status of a factor
    in his country,also displays the maximum and minimum value of this factor
    in the world.
```
Is it readable?
</blockquote></details>

```
In [37]: print(print_question.__doc__)                                                         

    Returns a question that asks the user about the status of a factor
    in his country,also displays the maximum and minimum value of this factor
    in the world.
    

```
Or is it readable?

**Comment by serhii73** [comment]
___
*[where.py, line 16 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkIzxZg8GnIGTpwKdDY:-LkJ-XXQ0B3bFM6iuMno:b7qw50j) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/where.py#L16)):*
<details><summary><i>Previously, serhii73 wrote…</i></summary><blockquote>

```
In [37]: print(print_question.__doc__)                                                         

    Returns a question that asks the user about the status of a factor
    in his country,also displays the maximum and minimum value of this factor
    in the world.
    

```
Or is it readable?
</blockquote></details>

Anyway, please read https://www.python.org/dev/peps/pep-0257/

**Comment by serhii73** [comment]
___
*[where.py, line 27 at r9](https://reviewable.io/reviews/serhii73/place2live/45#-LkJ08Ve7BColCLiS0tR:-LkJ08Ve7BColCLiS0tS:b-je2p5j) ([raw file](https://github.com/serhii73/place2live/blob/f6b075cd770ed8dba5ba849d2c9edd9cf5605a7a/where.py#L27)):*
> ```Python
>         second_value = max_min_value[0]
>     message = (
>         f"What is your {name_index} ({mood})? "
> ```

```
What is your desirable 
...
```

**Comment by serhii73** [comment]
Sorry, can you please fix conflicts @nikitaden03 ?

**Pull request merged**
