### PR TITLE
Military list and script added

### LINKED ISSUE #20: Scrape `List of countries by number of military and paramilitary personnel`
Scrape https://en.wikipedia.org/wiki/List_of_countries_by_number_of_military_and_paramilitary_personnel

### PR DESCRIPTION
**Pull request by gunjanraval**
Close #20

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/107)

### CODE REVIEW

**Comment by serhii73** [comment]
Hello @gunjanraval 
Thank you very much for your PR.
Can you remove `.DS_Store` files from this branch?

**Comment by gunjanraval** [comment]
@serhii73 Done!

**Comment by serhii73** [comment]
Sorry, this https://github.com/serhii73/place2live/blob/7870de791519d310dbec9b3c02647ad767097d1c/.DS_Store file needs to remove too.
Thank you very much!

**Comment by gunjanraval** [comment]
Done!

**Pull request merged**
