### PR TITLE
fix: Remove countries that don't have data in all columns

### PR DESCRIPTION
**Pull request by Sam1320**
Closes:#46

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/46)

### CODE REVIEW

**Comment by serhii73** [comment]
@Sam1320 
Thank you very much for your PR.
Please use [keywords](https://help.github.com/en/articles/closing-issues-using-keywords) for an automatically close issue.
Also, your [line](https://github.com/serhii73/place2live/blob/8db3c027fb2f162f5b645ac9f1d64d43ae4c82bb/where.py#L113) too long.
```
where.py:113:89: E501 line too long (90 > 88 characters)
```
What do you think about this code format?
```
print_out_df = out_df[
    [
        "country",
        "freedomhouse_score",
        "quality_of_life_index",
    ]
].dropna()
```

**Comment by Sam1320** [comment]
@serhii73  You're welcome!. 
I didn't know about the keywords, now I do, thanks for that.
About the code structure you proposed, I think its great with regard to readability. If you care about number of lines this would be another valid alternative:
```
print_out_df = out_df[["country", "freedomhouse_score", \
               "quality_of_life_index",]].dropna()

**Comment by serhii73** [comment]
> @serhii73 You're welcome!.
> I didn't know about the keywords, now I do, thanks for that.
> About the code structure you proposed, I think its great with regard to readability. If you care about number of lines this would be another valid alternative:
> 
> ```
> print_out_df = out_df[["country", "freedomhouse_score", \
>                "quality_of_life_index",]].dropna()
> ```

I think [it's](https://github.com/serhii73/place2live/pull/46#issuecomment-512543967) better =)

**Comment by Sam1320** [comment]
@serhii73 Done!

**Comment by serhii73** [comment]
> @serhii73 Done!

Thank you very much!

**Pull request merged**
