### PR TITLE
Features/add colorful

### PR DESCRIPTION
**Pull request by rosdyana**
Resolve Add colorful

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/90)

### CODE REVIEW

**Comment by serhii73** [comment]
Please use [keywords](https://help.github.com/en/articles/closing-issues-using-keywords) for an automatically close issue.

**Comment by serhii73** [comment]
Thank you very much for your PR.

**Comment by serhii73** [comment]
Can you please fix Travis errors?

**Comment by rosdyana** [comment]
> Can you please fix Travis errors?

Sure, no problem, thanks!

**Comment by serhii73** [comment]
Thank you very much for your PR.
I will review your PR in a few days.

**Comment by serhii73** [comment]
___
*[utils.py, line 17 at r8](https://reviewable.io/reviews/serhii73/place2live/90#-LqA_H2qDl8jfX-kRuqP:-LqA_H2qDl8jfX-kRuqQ:bvjf8yk) ([raw file](https://github.com/serhii73/place2live/blob/62786289592fba3cd5d45e19d564b57cb294a340/utils.py#L17)):*
> ```Python
>         return cf.red(text)
>     if txtType == text_type.QUESTION:
>         return cf.magenta(text)
> ```

What do you think if we change magenta to another? Maybe blue or light blue? Or your option?

**Comment by serhii73** [comment]
Screenshot from 2019-10-02 11-27-08
It is awesome. Thank you.
All code is perfect.
But if we change magenta to another it will be ideally. =)

**Comment by rosdyana** [comment]
> Screenshot from 2019-10-02 11-27-08
> It is awesome. Thank you.
> All code is perfect.
> But if we change magenta to another it will be ideally. =)

This is the result if we use blue color, I think it looks better with blue. 
image

**Comment by serhii73** [comment]
Thank you very much!
I merge it.
In the future, I think We can find the best color for this script.

**Comment by serhii73** [comment]
Close #78

**Pull request merged**
