### PR TITLE
Adding logo folder and logo suggestion

### PR DESCRIPTION
**Pull request by xavierrollet**
Ready for feedback

---
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/128)

### CODE REVIEW

**Comment by serhii73** [comment]
Thank you very much!
Your picture is very cool.
I like it.
But can we change colors?
Instead orange and black use blue and yellow?
This project uses Python programing language and yellow and blue good showing it =)
https://www.python.org/community/logos/
What do you think about that?

**Comment by xavierrollet** [comment]
logo3

**Comment by serhii73** [comment]
Thank you very much!

**Comment by xavierrollet** [comment]
You're welcome.

**Pull request merged**
