### PR TITLE
Uploaded Logo: Issue #125

### PR DESCRIPTION
**Pull request by vAporInside**
This change is [Reviewable](https://reviewable.io/reviews/serhii73/place2live/126)

### CODE REVIEW

**Comment by serhii73** [comment]
Thank you very much. It is awesome.
Do you have a more quality image?
Is it your picture? Wow. It's unbelievable.

**Comment by vAporInside** [comment]
Thank You! 😊
It's in vector format, so we can scale it:
p1logoshort

Also I have another logo :
logo2hires

I generated these images in Wix, edited it & finally converted it to vector format for scaling.

**Comment by serhii73** [comment]
> It's in vector format, so we can scale it:

Sorry, vector format is SVG? Right?
But in your PR only jpg file.
Can you send the vector format file?
Thank you very much!

**Comment by vAporInside** [comment]
Actually I created the vector format later so couldn't put that on PR.
I'll upload the SVG files by EOD.
Also do I need to create a new PR for that?

Thank You! 😊
(I'm new to this)

**Comment by serhii73** [comment]
> Actually I created the vector format later so couldn't put that on PR.
> I'll upload the SVG files by EOD.
> Also do I need to create a new PR for that?
> 
> Thank You! 
> (I'm new to this)

Yes. It will be awesome.
Thank you very much for your PR.

**Comment by serhii73** [comment]
You can create a folder in this project `logotype` for example.
And upload your SVG files =)
Thank you very much!
Your logo is brilliant.

**Comment by vAporInside** [comment]
Added logo vector files on PR#135 😊

**Comment by serhii73** [comment]
Thank you very much!

**Pull request merged**
